### ISSUE TITLE
omit ews.ip

### ISSUE THREAD

**Issue by t3chn0m4g3** [vorband/ewsposter#16]
currently we are using ews.ip on t-pot to skip `ip = ` in `ews.cfg`. Since ewsposter gets the external address anyway i think we could omit that.

**Comment by vorband** [comment]
reworked external ip routine in 22cf6df59523802b53178d277fbc532a99616497

during startup, ewsposter will use the following steps to determine a valid public IP, in that order: 
- use env variable MY_EXTIP
- use ip from ews.ip
- use ip from ews.cfg 
- use public service 

As soon as it got a valid public ip from the steps above, the public ip is set and the subsequent steps are skipped. If none of the above steps lead to a valid public IP work, ewsposter will fail to start. 
 
Note that the public IP is not verified, so whatever is used in env variable MY_EXTIP, ews.cfg and ews.ip sections will be set, as long as it is a valid public IP. 

Please test and close.

**Comment by t3chn0m4g3** [comment]
Works as expected. For future reference see the following output:

```
EWS Poster v1.9.5 (c) by Markus Schroer <markus.schroer@telekom.de>

 => Create ews.idx counterfile
 => Using external IP address 8x.1x.4x.1x
 => Create lock socket successfull.
 => Sender : No Jobs to send in /opt/ewsposter/spool/
```
