### ISSUE TITLE
Support Tanner Logfiles / Downloaded malware

### ISSUE THREAD

**Issue by t3chn0m4g3** [vorband/ewsposter#9]
Snare / Tanner is the latest addition to T-Pot.

While Snare only emulates the webpages, Tanner is the logic behind Snare that does the heavy lifting with regard to logging and downloading the remote malware.

Malware is stored in a folder named `files`, there is no hash, no known log reference, just the plain, requested file i.e. from an RFI. Simply put it might be a remote webpage, an executable or something else.

Example log file, please rename to `.json`:
[tanner_report.json.txt](https://github.com/vorband/ewsposter/files/2052840/tanner_report.json.txt)

**Comment by vorband** [comment]
implemented in 4bad62eaf86fb602e62e76ce14cc59a2b2bb5b84
malware submission is currently not implemented, as there is no reference to the attack.

**Comment by t3chn0m4g3** [comment]
LGTM
